channels:
  - conda-forge
dependencies:
  - python==3.7
  - sphinx
  - pandoc
  - nbconvert 
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - pytest
  - emcee
  - dynesty
  - pint
  - uncertainties
  - pip
  - pip:
    - nbsphinx
    - jupyter-sphinx
    - sphinx_rtd_theme
    - tqdm